// Database completo degli alimenti per la dieta pancia piatta
const dietaDB = {
  "categorie": {
    "proteine": {
      "nome": "Proteine",
      "descrizione": "Fonti proteiche principali",
      "alimenti": [
        {
          "id": "pollo_grigliato",
          "nome": "Pollo grigliato",
          "categoria": "proteine",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 165,
          "proteine_per_100g": 31,
          "grassi_per_100g": 3.6,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "zuccheri_per_100g": 0,
          "grassi_saturi_per_100g": 1,
          "sodio_per_100g": 74,
          "potassio_per_100g": 256,
          "calcio_per_100g": 15,
          "ferro_per_100g": 1.3,
          "vitamina_c_per_100g": 0,
          "colesterolo_per_100g": 85,
          "indice_glicemico": 0,
          "tipo": "carne_bianca"
        },
        {
          "id": "tacchino_grigliato",
          "nome": "Tacchino grigliato",
          "categoria": "proteine",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 135,
          "proteine_per_100g": 29,
          "grassi_per_100g": 1.5,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "zuccheri_per_100g": 0,
          "grassi_saturi_per_100g": 0.4,
          "sodio_per_100g": 65,
          "indice_glicemico": 0,
          "tipo": "carne_bianca"
        },
        {
          "id": "merluzzo_vapore",
          "nome": "Merluzzo al vapore",
          "categoria": "proteine",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 82,
          "proteine_per_100g": 18,
          "grassi_per_100g": 0.7,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "zuccheri_per_100g": 0,
          "grassi_saturi_per_100g": 0.1,
          "sodio_per_100g": 54,
          "indice_glicemico": 0,
          "tipo": "pesce_bianco"
        },
        {
          "id": "orata_forno",
          "nome": "Orata al forno",
          "categoria": "proteine",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 135,
          "proteine_per_100g": 20.5,
          "grassi_per_100g": 5.5,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "sodio_per_100g": 49,
          "indice_glicemico": 0,
          "tipo": "pesce_bianco"
        },
        {
          "id": "branzino_forno",
          "nome": "Branzino al forno",
          "categoria": "proteine",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 124,
          "proteine_per_100g": 23.5,
          "grassi_per_100g": 2.5,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "sodio_per_100g": 70,
          "indice_glicemico": 0,
          "tipo": "pesce_bianco"
        },
        {
          "id": "sgombro_naturale",
          "nome": "Sgombro al naturale",
          "categoria": "proteine",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 205,
          "proteine_per_100g": 19,
          "grassi_per_100g": 14,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "sodio_per_100g": 90,
          "omega3_per_100g": 2.3,
          "indice_glicemico": 0,
          "tipo": "pesce_azzurro"
        },
        {
          "id": "tonno_fresco",
          "nome": "Tonno fresco",
          "categoria": "proteine",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 144,
          "proteine_per_100g": 23,
          "grassi_per_100g": 5,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "sodio_per_100g": 39,
          "omega3_per_100g": 1.4,
          "indice_glicemico": 0,
          "tipo": "pesce_azzurro"
        },
        {
          "id": "uova",
          "nome": "Uova",
          "categoria": "proteine",
          "porzione_standard": 2,
          "unita_misura": "unità",
          "calorie_per_unita": 68,
          "proteine_per_unita": 6.3,
          "grassi_per_unita": 4.8,
          "carboidrati_per_unita": 0.6,
          "fibre_per_unita": 0,
          "colesterolo_per_unita": 186,
          "indice_glicemico": 0,
          "tipo": "uova"
        },
        {
          "id": "carne_rossa_magra",
          "nome": "Carne rossa magra",
          "categoria": "proteine",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 135,
          "proteine_per_100g": 26,
          "grassi_per_100g": 3,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "ferro_per_100g": 2.6,
          "zinco_per_100g": 4.8,
          "indice_glicemico": 0,
          "tipo": "carne_rossa"
        }
      ]
    },
    "carboidrati": {
      "nome": "Carboidrati",
      "descrizione": "Fonti di carboidrati complessi",
      "alimenti": [
        {
          "id": "farro_perlato",
          "nome": "Farro perlato",
          "categoria": "carboidrati",
          "porzione_standard": 40,
          "unita_misura": "g",
          "calorie_per_100g": 335,
          "proteine_per_100g": 10.5,
          "grassi_per_100g": 2.1,
          "carboidrati_per_100g": 67,
          "fibre_per_100g": 6.8,
          "indice_glicemico": 45,
          "tipo": "cereali"
        },
        {
          "id": "orzo_perlato",
          "nome": "Orzo perlato",
          "categoria": "carboidrati",
          "porzione_standard": 40,
          "unita_misura": "g",
          "calorie_per_100g": 354,
          "proteine_per_100g": 10.5,
          "grassi_per_100g": 2.1,
          "carboidrati_per_100g": 73,
          "fibre_per_100g": 15.6,
          "indice_glicemico": 25,
          "tipo": "cereali"
        },
        {
          "id": "riso_basmati",
          "nome": "Riso basmati",
          "categoria": "carboidrati",
          "porzione_standard": 40,
          "unita_misura": "g",
          "calorie_per_100g": 360,
          "proteine_per_100g": 9,
          "grassi_per_100g": 0.9,
          "carboidrati_per_100g": 78,
          "fibre_per_100g": 1.3,
          "indice_glicemico": 58,
          "tipo": "cereali"
        },
        {
          "id": "riso_integrale",
          "nome": "Riso integrale",
          "categoria": "carboidrati",
          "porzione_standard": 40,
          "unita_misura": "g",
          "calorie_per_100g": 370,
          "proteine_per_100g": 7.5,
          "grassi_per_100g": 2.9,
          "carboidrati_per_100g": 77.2,
          "fibre_per_100g": 3.5,
          "indice_glicemico": 50,
          "tipo": "cereali"
        },
        {
          "id": "patata_dolce",
          "nome": "Patata dolce",
          "categoria": "carboidrati",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 86,
          "proteine_per_100g": 1.6,
          "grassi_per_100g": 0.1,
          "carboidrati_per_100g": 20.1,
          "fibre_per_100g": 3,
          "zuccheri_per_100g": 4.2,
          "vitamina_a_per_100g": 709,
          "indice_glicemico": 70,
          "tipo": "tuberi"
        },
        {
          "id": "wasa",
          "nome": "Wasa",
          "categoria": "carboidrati",
          "porzione_standard": 2,
          "unita_misura": "fette",
          "calorie_per_fetta": 35,
          "proteine_per_fetta": 1.2,
          "grassi_per_fetta": 0.4,
          "carboidrati_per_fetta": 6.5,
          "fibre_per_fetta": 1.7,
          "indice_glicemico": 50,
          "tipo": "crackers"
        },
        {
          "id": "crackers_integrali",
          "nome": "Crackers integrali",
          "categoria": "carboidrati",
          "porzione_standard": 2,
          "unita_misura": "unità",
          "calorie_per_unita": 30,
          "proteine_per_unita": 1,
          "grassi_per_unita": 1,
          "carboidrati_per_unita": 5,
          "fibre_per_unita": 0.5,
          "indice_glicemico": 55,
          "tipo": "crackers"
        }
      ]
    },
    "verdure": {
      "nome": "Verdure",
      "descrizione": "Verdure crude e cotte",
      "alimenti": [
        {
          "id": "fagiolini",
          "nome": "Fagiolini",
          "categoria": "verdure",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 31,
          "proteine_per_100g": 1.8,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 7,
          "fibre_per_100g": 2.7,
          "vitamina_c_per_100g": 12.2,
          "indice_glicemico": 15,
          "tipo": "verdura_cotta"
        },
        {
          "id": "carote",
          "nome": "Carote",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 41,
          "proteine_per_100g": 0.9,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 9.6,
          "fibre_per_100g": 2.8,
          "vitamina_a_per_100g": 835,
          "beta_carotene_per_100g": 8285,
          "indice_glicemico": 47,
          "tipo": "verdura_mista"
        },
        {
          "id": "spinaci",
          "nome": "Spinaci",
          "categoria": "verdure",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 23,
          "proteine_per_100g": 2.9,
          "grassi_per_100g": 0.4,
          "carboidrati_per_100g": 3.6,
          "fibre_per_100g": 2.2,
          "ferro_per_100g": 2.7,
          "vitamina_k_per_100g": 483,
          "indice_glicemico": 15,
          "tipo": "verdura_mista"
        },
        {
          "id": "zucchine",
          "nome": "Zucchine",
          "categoria": "verdure",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 17,
          "proteine_per_100g": 1.2,
          "grassi_per_100g": 0.3,
          "carboidrati_per_100g": 3.1,
          "fibre_per_100g": 1,
          "vitamina_c_per_100g": 17.9,
          "indice_glicemico": 15,
          "tipo": "verdura_cotta"
        },
        {
          "id": "bietole",
          "nome": "Bietole",
          "categoria": "verdure",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 19,
          "proteine_per_100g": 1.8,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 3.7,
          "fibre_per_100g": 1.6,
          "vitamina_k_per_100g": 830,
          "indice_glicemico": 15,
          "tipo": "verdura_cotta"
        },
        {
          "id": "finocchi",
          "nome": "Finocchi",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 31,
          "proteine_per_100g": 1.2,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 7.3,
          "fibre_per_100g": 3.1,
          "potassio_per_100g": 414,
          "indice_glicemico": 15,
          "tipo": "verdura_mista"
        },
        {
          "id": "lattuga",
          "nome": "Lattuga",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 15,
          "proteine_per_100g": 1.4,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 2.9,
          "fibre_per_100g": 1.3,
          "vitamina_k_per_100g": 102.5,
          "indice_glicemico": 10,
          "tipo": "verdura_cruda"
        },
        {
          "id": "rucola",
          "nome": "Rucola",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 25,
          "proteine_per_100g": 2.6,
          "grassi_per_100g": 0.7,
          "carboidrati_per_100g": 3.7,
          "fibre_per_100g": 1.6,
          "calcio_per_100g": 160,
          "indice_glicemico": 15,
          "tipo": "verdura_cruda"
        },
        {
          "id": "cetrioli",
          "nome": "Cetrioli",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 16,
          "proteine_per_100g": 0.7,
          "grassi_per_100g": 0.1,
          "carboidrati_per_100g": 3.6,
          "fibre_per_100g": 0.5,
          "vitamina_k_per_100g": 16.4,
          "indice_glicemico": 15,
          "tipo": "verdura_cruda"
        },
        {
          "id": "peperoni_grigliati",
          "nome": "Peperoni grigliati",
          "categoria": "verdure",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 30,
          "proteine_per_100g": 1,
          "grassi_per_100g": 0.3,
          "carboidrati_per_100g": 6,
          "fibre_per_100g": 2.1,
          "vitamina_c_per_100g": 127.7,
          "indice_glicemico": 15,
          "tipo": "verdura_cotta"
        },
        {
          "id": "sedano",
          "nome": "Sedano",
          "categoria": "verdure",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 16,
          "proteine_per_100g": 0.7,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 3,
          "fibre_per_100g": 1.6,
          "potassio_per_100g": 260,
          "indice_glicemico": 15,
          "tipo": "verdura_cruda"
        }
      ]
    },
    "frutta": {
      "nome": "Frutta",
      "descrizione": "Frutta fresca",
      "alimenti": [
        {
          "id": "mela",
          "nome": "Mela",
          "categoria": "frutta",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 52,
          "proteine_per_100g": 0.3,
          "grassi_per_100g": 0.2,
          "carboidrati_per_100g": 13.8,
          "fibre_per_100g": 2.4,
          "zuccheri_per_100g": 10.4,
          "vitamina_c_per_100g": 4.6,
          "indice_glicemico": 36,
          "tipo": "frutta_fresca"
        },
        {
          "id": "pera",
          "nome": "Pera",
          "categoria": "frutta",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 57,
          "proteine_per_100g": 0.4,
          "grassi_per_100g": 0.1,
          "carboidrati_per_100g": 15.2,
          "fibre_per_100g": 3.1,
          "zuccheri_per_100g": 9.8,
          "potassio_per_100g": 116,
          "indice_glicemico": 38,
          "tipo": "frutta_fresca"
        },
        {
          "id": "banana",
          "nome": "Banana",
          "categoria": "frutta",
          "porzione_standard": 120,
          "unita_misura": "g",
          "calorie_per_100g": 89,
          "proteine_per_100g": 1.1,
          "grassi_per_100g": 0.3,
          "carboidrati_per_100g": 22.8,
          "fibre_per_100g": 2.6,
          "zuccheri_per_100g": 12.2,
          "potassio_per_100g": 358,
          "vitamina_b6_per_100g": 0.4,
          "indice_glicemico": 51,
          "tipo": "frutta_fresca"
        },
        {
          "id": "kiwi",
          "nome": "Kiwi",
          "categoria": "frutta",
          "porzione_standard": 100,
          "unita_misura": "g",
          "calorie_per_100g": 61,
          "proteine_per_100g": 1.1,
          "grassi_per_100g": 0.5,
          "carboidrati_per_100g": 14.7,
          "fibre_per_100g": 3,
          "zuccheri_per_100g": 9,
          "vitamina_c_per_100g": 92.7,
          "vitamina_e_per_100g": 1.5,
          "indice_glicemico": 53,
          "tipo": "frutta_fresca"
        },
        {
          "id": "frutti_bosco",
          "nome": "Frutti di bosco",
          "categoria": "frutta",
          "porzione_standard": 150,
          "unita_misura": "g",
          "calorie_per_100g": 43,
          "proteine_per_100g": 0.7,
          "grassi_per_100g": 0.5,
          "carboidrati_per_100g": 9.6,
          "fibre_per_100g": 3.6,
          "zuccheri_per_100g": 4.4,
          "vitamina_c_per_100g": 21,
          "antociani_per_100g": 163,
          "indice_glicemico": 25,
          "tipo": "frutta_fresca"
        }
      ]
    },
    "frutta_secca": {
      "nome": "Frutta Secca",
      "descrizione": "Frutta secca e semi oleosi",
      "alimenti": [
        {
          "id": "mandorle",
          "nome": "Mandorle",
          "categoria": "frutta_secca",
          "porzione_standard": 25,
          "unita_misura": "g",
          "calorie_per_100g": 579,
          "proteine_per_100g": 21.2,
          "grassi_per_100g": 49.9,
          "carboidrati_per_100g": 21.6,
          "fibre_per_100g": 12.5,
          "vitamina_e_per_100g": 25.6,
          "magnesio_per_100g": 270,
          "indice_glicemico": 15,
          "tipo": "frutta_secca"
        },
        {
          "id": "noci",
          "nome": "Noci",
          "categoria": "frutta_secca",
          "porzione_standard": 20,
          "unita_misura": "g",
          "calorie_per_100g": 654,
          "proteine_per_100g": 15.2,
          "grassi_per_100g": 65.2,
          "carboidrati_per_100g": 13.7,
          "fibre_per_100g": 6.7,
          "omega3_per_100g": 9.1,
          "magnesio_per_100g": 158,
          "indice_glicemico": 15,
          "tipo": "frutta_secca"
        },
        {
          "id": "nocciole",
          "nome": "Nocciole",
          "categoria": "frutta_secca",
          "porzione_standard": 25,
          "unita_misura": "g",
          "calorie_per_100g": 628,
          "proteine_per_100g": 15,
          "grassi_per_100g": 60.8,
          "carboidrati_per_100g": 16.7,
          "fibre_per_100g": 9.7,
          "vitamina_e_per_100g": 15,
          "folati_per_100g": 113,
          "indice_glicemico": 15,
          "tipo": "frutta_secca"
        },
        {
          "id": "pistacchi",
          "nome": "Pistacchi",
          "categoria": "frutta_secca",
          "porzione_standard": 25,
          "unita_misura": "g",
          "calorie_per_100g": 560,
          "proteine_per_100g": 20.2,
          "grassi_per_100g": 45.3,
          "carboidrati_per_100g": 27.2,
          "fibre_per_100g": 10.6,
          "vitamina_b6_per_100g": 1.7,
          "potassio_per_100g": 1025,
          "indice_glicemico": 15,
          "tipo": "frutta_secca"
        },
        {
          "id": "anacardi",
          "nome": "Anacardi",
          "categoria": "frutta_secca",
          "porzione_standard": 15,
          "unita_misura": "g",
          "calorie_per_100g": 553,
          "proteine_per_100g": 18.2,
          "grassi_per_100g": 43.8,
          "carboidrati_per_100g": 30.2,
          "fibre_per_100g": 3.3,
          "ferro_per_100g": 6.7,
          "zinco_per_100g": 5.8,
          "indice_glicemico": 22,
          "tipo": "frutta_secca"
        }
      ]
    },
    "grassi_condimenti": {
      "nome": "Grassi e Condimenti",
      "descrizione": "Oli, burri e condimenti",
      "alimenti": [
        {
          "id": "olio_evo",
          "nome": "Olio EVO",
          "categoria": "grassi_condimenti",
          "porzione_standard": 5,
          "unita_misura": "g",
          "calorie_per_100g": 884,
          "proteine_per_100g": 0,
          "grassi_per_100g": 100,
          "carboidrati_per_100g": 0,
          "fibre_per_100g": 0,
          "vitamina_e_per_100g": 14.4,
          "vitamina_k_per_100g": 60.2,
          "polifenoli_per_100g": 300,
          "indice_glicemico": 0,
          "tipo": "olio"
        },
        {
          "id": "burro_arachidi",
          "nome": "Burro di arachidi",
          "categoria": "grassi_condimenti",
          "porzione_standard": 15,
          "unita_misura": "g",
          "calorie_per_100g": 588,
          "proteine_per_100g": 25.1,
          "grassi_per_100g": 50.4,
          "carboidrati_per_100g": 19.6,
          "fibre_per_100g": 8,
          "zuccheri_per_100g": 9.2,
          "magnesio_per_100g": 154,
          "indice_glicemico": 14,
          "tipo": "burro_vegetale"
        }
      ]
    },
    "legumi": {
      "nome": "Legumi",
      "descrizione": "Legumi decorticati",
      "alimenti": [
        {
          "id": "legumi_decorticati",
          "nome": "Legumi decorticati misti",
          "categoria": "legumi",
          "porzione_standard": 60,
          "unita_misura": "g",
          "calorie_per_100g": 325,
          "proteine_per_100g": 22,
          "grassi_per_100g": 1.2,
          "carboidrati_per_100g": 55,
          "fibre_per_100g": 11,
          "ferro_per_100g": 6.5,
          "folati_per_100g": 358,
          "indice_glicemico": 30,
          "tipo": "legumi_secchi"
        }
      ]
    },
    "bevande": {
      "nome": "Bevande",
      "descrizione": "Tisane e bevande",
      "alimenti": [
        {
          "id": "tisana_finocchio",
          "nome": "Tisana al finocchio",
          "categoria": "bevande",
          "porzione_standard": 250,
          "unita_misura": "ml",
          "calorie_per_100ml": 1,
          "proteine_per_100ml": 0,
          "grassi_per_100ml": 0,
          "carboidrati_per_100ml": 0.2,
          "fibre_per_100ml": 0,
          "indice_glicemico": 0,
          "tipo": "tisana"
        },
        {
          "id": "tisana_drenante",
          "nome": "Tisana drenante",
          "categoria": "bevande",
          "porzione_standard": 250,
          "unita_misura": "ml",
          "calorie_per_100ml": 1,
          "proteine_per_100ml": 0,
          "grassi_per_100ml": 0,
          "carboidrati_per_100ml": 0.2,
          "fibre_per_100ml": 0,
          "indice_glicemico": 0,
          "tipo": "tisana"
        },
        {
          "id": "te_verde",
          "nome": "Tè verde",
          "categoria": "bevande",
          "porzione_standard": 250,
          "unita_misura": "ml",
          "calorie_per_100ml": 1,
          "proteine_per_100ml": 0.2,
          "grassi_per_100ml": 0,
          "carboidrati_per_100ml": 0,
          "fibre_per_100ml": 0,
          "caffeina_per_100ml": 25,
          "polifenoli_per_100ml": 89,
          "indice_glicemico": 0,
          "tipo": "te"
        }
      ]
    }
  },
  "metadata": {
    "versione": "2.0",
    "ultima_modifica": "2025-01-10",
    "note": "Database ottimizzato per web app con valori nutrizionali essenziali"
  }
};

// Funzione per salvare il database in localStorage
function saveDatabase() {
  localStorage.setItem('dietaDB', JSON.stringify(dietaDB));
}

// Funzione per caricare il database da localStorage
function loadDatabase() {
  const saved = localStorage.getItem('dietaDB');
  if (saved) {
    return JSON.parse(saved);
  }
  return dietaDB;
}

// Esporta per uso in altri file
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { dietaDB, saveDatabase, loadDatabase };
}
